spring.application.name=login-service

## MSSQL Connection
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=testdb;encrypt=true;trustServerCertificate=true
#spring.datasource.username=sa
#spring.datasource.password=your_password
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#
## JPA Settings
#spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

server.port=${PORT:8080}
spring.r2dbc.url=r2dbc:sqlserver://localhost:1433/login_db
spring.r2dbc.username=redajaffar
spring.r2dbc.password=Admin@123
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=20